### ISSUE TITLE
LogoScene 제작

### ISSUE THREAD

**Issue by SoinDosa** [SoinDosa/Project_FS#3]
# LogoScene
* 게임을 시작하면 설정값, UI String, 점수를 로드
* 6초 후 LobbyScene으로 이동
# TODO
- [x] 임시 로고 삽입
- [x] 임시 데이터 생성/로드
    * 설정값
        * isOnBGM:bool(default = true)
        * isOnEFX:bool(default = true)
        * language:int(default = 0)
    * UI string:Dictionary<string, string>
        * NewtonSoft의 JsonConvertor Library 사용
    * 점수
        * score:int(default = 0)
- [x] 페이드인/페이드아웃 기능
    * DOTween Library 사용 
- [x] 6초후 LobbyScene으로 이동
